### ISSUE TITLE
Fatal: unable to access 'https://github.com/zhanghang1989/PyTorch-Encoding/': Failed to connect to github.com port 443: 连接超时

### ISSUE THREAD

**Issue by king1111sadjfoisja** [sharinka0715/semantic-gaussians#12]
Hi,when i was trying to 
`pip install -r requirements.txt`
the following messages appear:
![image](https://github.com/user-attachments/assets/3649b0f1-fc3d-40cc-ad42-b058ff186cf8)
`fatal: unable to access 'https://github.com/zhanghang1989/PyTorch-Encoding/': Failed to connect to github.com port 443: 连接超时`
I am using the internet in China.
 Could this issue possibly be due to network problems? 
However, I'm not entirely sure. Do you have any suitable alternative solutions?

If so, I would greatly appreciate it!Looking forward to your reply.

**Comment by king1111sadjfoisja** [comment]
Besides, I am connecting to an Ubuntu server via SSH.
Looking forward to your reply！！！

**Comment by king1111sadjfoisja** [comment]
Besides, I am connecting to an Ubuntu server via SSH.
Looking forward to your reply！！！

**Comment by sharinka0715** [comment]
Hi,

It is no doubt that the issue you've encountered is due to your network. You may need to use a proxy to get over the network problem.

Additionally, GitHub issues should be used to track problems of the repository. Issues that are apparently not related to our Semantic Gaussians might not be replied any more. Hope you could understand.

**Comment by king1111sadjfoisja** [comment]
Got it, thank you.
