### ISSUE TITLE
Question about Training Efficiency for Multiple Scenes in ScanNet

### ISSUE THREAD

**Issue by tj12323** [sharinka0715/semantic-gaussians#26]
Thank you for sharing this impressive work and the detailed implementation. While reviewing the code and the paper, I encountered a question regarding the training process for multiple scenes.

From my exploration of `train.py`, I noticed that the script supports training only one scene at a time, and it takes approximately 1.5 hours to complete the training for a single scene(
![微信截图_20241214211736](https://github.com/user-attachments/assets/ba6d2b60-5263-411d-98ad-42fa6e5a20ef)
). However, in the paper, you mentioned that you trained 3D RGB Gaussians for all 1201 scenes in the ScanNet dataset. 
Given the time required per scene, this suggests that training all scenes sequentially would take several weeks. Could you clarify how you achieved this? Specifically:
1. Did you use a distributed training setup or parallelized the process across multiple GPUs/machines?
2. If there were optimizations to speed up the process, could you provide any insights or recommendations?

Thank you for your time, and I appreciate any guidance you can provide regarding this matter.

**Comment by sharinka0715** [comment]
Admittedly, training RGB 3DGS on all 1,201 scenes in the ScanNet dataset is time-consuming. In our experiments, we only train 10,000 steps for each scene rather than 30,000 steps to spare time. The resolution of input images are [648, 484] and frame interval is 5. We train our RGB 3DGS by simutaneously running 8 training process on 8 GPUs, which costs nearly one week.

If you feel awkward to training and distill all scenes on ScanNet dataset, we recommend you to only use 2D projection results. The performance won't differ too much, but it's much more time-efficient and friendly.

**Comment by tj12323** [comment]
Thank you so much for your detailed response!
